### ISSUE TITLE
Xfer the project over to the XboxAPI organisation

### ISSUE THREAD

**Issue by djekl** [audibleblink/xbox-api#2]
As discussed on Twitter, I have added you to the organisation you just need to transfer the repo over.

You will still be the owner, but it just keeps the code in one place for others to find.

https://twitter.com/4lex/status/557659669049905153

**Comment by audibleblink** [comment]
It's telling me I don't have admin rights on the receiving org.

https://www.dropbox.com/s/guq9rxdgeq13wjg/Screenshot%202015-01-22%2023.21.09.png?dl=0

**Comment by djekl** [comment]
Give me access to this repo and I can move it over for you

**Comment by djekl** [comment]
I cant move the repo myself, have made you admin so you can move. no need to duplicate as this should redirect to it

**Comment by audibleblink** [comment]
I can't rename the repo. I've got links out there to this repo's url that I'd rather not change, hence the duplication. I'll move @audibleblink./xbox-api-wrapper-gem

**Comment by djekl** [comment]
When you move the repo, cant you setup a redirect? I am just thinking of maintenance is all

**Comment by audibleblink** [comment]
I didn't see that option. I've got both remotes anyway. Maintenance shouldn't be an issue.

**Comment by djekl** [comment]
Ahh ok, if your happy to maintain then I am happy with that
